### ISSUE TITLE
Unhandled exception due to a hard-coded file path

### ISSUE THREAD

**Issue by Apticle** [BJDubb/SirenSharp#3]
This occurs when attempting to generate the FiveM resource
![image](https://github.com/BJDubb/SirenSharp/assets/76893282/9877f9a9-9fc2-4b7d-b185-9ba60c09e403)

**Comment by ATG-Github** [comment]
Fixed in master.

**Comment by BJDubb** [comment]
This has been fixed in the lastest [release](https://github.com/BJDubb/SirenSharp/releases/tag/v0.2.1)
